from . import dispatch_utils
from . import delivery_zone
from . import delivery_point
from . import delivery_partner_profile
from . import delivery_plan_day
from . import delivery_trip
from . import delivery_trip_stop
from . import delivery_trip_registration
from . import delivery_profile_task
from . import fleet_vehicle
from . import res_partner
from . import res_users
from . import sale_order
from . import stock_picking
from . import stock_warehouse
from . import delivery_planner_snapshot
from . import dispatch_import_wizard
