[
  {
    "ID": 191,
    "ProductCategoryName": "BULONGOCVIT",
    "ProductCategoryCode": "BULONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0008",
    "Children": [
      {
        "ID": 257,
        "ProductCategoryName": "Bu lông máy",
        "ProductCategoryCode": "BULONGMAY",
        "Inactive": false,
        "ParentProductCategoryID": 191,
        "ParentProductCategoryIDText": "BULONGOCVIT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 191,
        "MISACode": "0008/0010",
        "Children": [],
        "ProductCategoryNameAndCode": "Bu lông máy (BULONGMAY)"
      },
      {
        "ID": 258,
        "ProductCategoryName": "Bulong xây dựng",
        "ProductCategoryCode": "BULONGXD",
        "Inactive": false,
        "ParentProductCategoryID": 191,
        "ParentProductCategoryIDText": "BULONGOCVIT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 191,
        "MISACode": "0008/0012",
        "Children": [],
        "ProductCategoryNameAndCode": "Bulong xây dựng (BULONGXD)"
      },
      {
        "ID": 192,
        "ProductCategoryName": "ĐINH VÍT CÁC LOẠI",
        "ProductCategoryCode": "DINHVIT",
        "Inactive": false,
        "ParentProductCategoryID": 191,
        "ParentProductCategoryIDText": "BULONGOCVIT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 191,
        "MISACode": "0008/0013",
        "Children": [],
        "ProductCategoryNameAndCode": "ĐINH VÍT CÁC LOẠI (DINHVIT)"
      }
    ],
    "ProductCategoryNameAndCode": "BULONGOCVIT (BULONG)"
  },
  {
    "ID": 193,
    "ProductCategoryName": "CÔNG CỤ DỤNG CỤ CẦM TAY",
    "ProductCategoryCode": "CONGCUDUNGCU",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0013",
    "Children": [
      {
        "ID": 252,
        "ProductCategoryName": "Cờ lê lực",
        "ProductCategoryCode": "COLELUC",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0013",
        "Children": [],
        "ProductCategoryNameAndCode": "Cờ lê lực (COLELUC)"
      },
      {
        "ID": 197,
        "ProductCategoryName": "Dụng cụ cầm tay ASAKI",
        "ProductCategoryCode": "ASAKI",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0014",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay ASAKI (ASAKI)"
      },
      {
        "ID": 251,
        "ProductCategoryName": "Dụng cụ cầm tay cao cấp",
        "ProductCategoryCode": "DUNGCUCAOCAP",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0015",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay cao cấp (DUNGCUCAOCAP)"
      },
      {
        "ID": 198,
        "ProductCategoryName": "Dụng cụ cầm tay khác",
        "ProductCategoryCode": "DUNGCUKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0016",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay khác (DUNGCUKHAC)"
      },
      {
        "ID": 250,
        "ProductCategoryName": "Dụng cụ cầm tay không thương hiệu",
        "ProductCategoryCode": "DUNGCUGIARE",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0017",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay không thương hiệu (DUNGCUGIARE)"
      },
      {
        "ID": 236,
        "ProductCategoryName": "Dụng cụ cầm tay KINGTONY",
        "ProductCategoryCode": "KINGTONY",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0018",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay KINGTONY (KINGTONY)"
      },
      {
        "ID": 249,
        "ProductCategoryName": "Dụng cụ cầm tay loại thường có thương hiệu",
        "ProductCategoryCode": "DUNGCUTHUONG",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0019",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay loại thường có thương hiệu (DUNGCUTHUONG)"
      },
      {
        "ID": 157,
        "ProductCategoryName": "Dụng cụ cầm tay SATA",
        "ProductCategoryCode": "SATA",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0020",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay SATA (SATA)"
      },
      {
        "ID": 248,
        "ProductCategoryName": "Dụng cụ cầm tay thương hiệu tầm trung",
        "ProductCategoryCode": "DUNGCUTAMTRUNG",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0021",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay thương hiệu tầm trung (DUNGCUTAMTRUNG)"
      },
      {
        "ID": 195,
        "ProductCategoryName": "Dụng cụ cầm tay TOLSEN",
        "ProductCategoryCode": "TOLSEN",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0022",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay TOLSEN (TOLSEN)"
      },
      {
        "ID": 196,
        "ProductCategoryName": "Dụng cụ cầm tay TONE",
        "ProductCategoryCode": "TONE",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0023",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay TONE (TONE)"
      },
      {
        "ID": 194,
        "ProductCategoryName": "Dụng cụ cầm tay TOTAL & INGCO",
        "ProductCategoryCode": "TOTAL & INGCO",
        "Inactive": false,
        "ParentProductCategoryID": 193,
        "ParentProductCategoryIDText": "CÔNG CỤ DỤNG CỤ CẦM TAY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 193,
        "MISACode": "0013/0024",
        "Children": [],
        "ProductCategoryNameAndCode": "Dụng cụ cầm tay TOTAL & INGCO (TOTAL & INGCO)"
      }
    ],
    "ProductCategoryNameAndCode": "CÔNG CỤ DỤNG CỤ CẦM TAY (CONGCUDUNGCU)"
  },
  {
    "ID": 2,
    "ProductCategoryName": "DANH MỤC KHÁC",
    "ProductCategoryCode": "DANHMUCKHAC",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0016",
    "Children": [
      {
        "ID": 55,
        "ProductCategoryName": "DUNG DỊCH",
        "ProductCategoryCode": "DUNGDICH",
        "Inactive": false,
        "ParentProductCategoryID": 2,
        "ParentProductCategoryIDText": "DANH MỤC KHÁC",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 2,
        "MISACode": "0016/0020",
        "Children": [],
        "ProductCategoryNameAndCode": "DUNG DỊCH (DUNGDICH)"
      }
    ],
    "ProductCategoryNameAndCode": "DANH MỤC KHÁC (DANHMUCKHAC)"
  },
  {
    "ID": 61,
    "ProductCategoryName": "DẦU MỠ",
    "ProductCategoryCode": "DAUMO",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0018",
    "Children": [
      {
        "ID": 204,
        "ProductCategoryName": "DẦU MỠ KHÁC",
        "ProductCategoryCode": "MOKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 61,
        "ParentProductCategoryIDText": "DẦU MỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 61,
        "MISACode": "0018/0018",
        "Children": [],
        "ProductCategoryNameAndCode": "DẦU MỠ KHÁC (MOKHAC)"
      },
      {
        "ID": 202,
        "ProductCategoryName": "Dầu mỡ MOBIL, SHELL",
        "ProductCategoryCode": "MOBIL, SHELL",
        "Inactive": false,
        "ParentProductCategoryID": 61,
        "ParentProductCategoryIDText": "DẦU MỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 61,
        "MISACode": "0018/0021",
        "Children": [],
        "ProductCategoryNameAndCode": "Dầu mỡ MOBIL, SHELL (MOBIL, SHELL)"
      }
    ],
    "ProductCategoryNameAndCode": "DẦU MỠ (DAUMO)"
  },
  {
    "ID": 136,
    "ProductCategoryName": "DÂY CU ROA, PU LY VÀ NHÔNG XÍCH",
    "ProductCategoryCode": "PM_DAYCUROAPULYNHONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0021",
    "Children": [],
    "ProductCategoryNameAndCode": "DÂY CU ROA, PU LY VÀ NHÔNG XÍCH (PM_DAYCUROAPULYNHONG)"
  },
  {
    "ID": 30,
    "ProductCategoryName": "DÂY CUROA, BĂNG TẢI, SIN PHỐT",
    "ProductCategoryCode": "DAYCUROABTSP",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0022",
    "Children": [
      {
        "ID": 43,
        "ProductCategoryName": "Dây curoa BANDO",
        "ProductCategoryCode": "BANDO",
        "Inactive": false,
        "ParentProductCategoryID": 30,
        "ParentProductCategoryIDText": "DÂY CUROA, BĂNG TẢI, SIN PHỐT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 30,
        "MISACode": "0022/0022",
        "Children": [],
        "ProductCategoryNameAndCode": "Dây curoa BANDO (BANDO)"
      },
      {
        "ID": 17,
        "ProductCategoryName": "Dây curoa MITSUBOSHI",
        "ProductCategoryCode": "MITSUBOSHI",
        "Inactive": false,
        "ParentProductCategoryID": 30,
        "ParentProductCategoryIDText": "DÂY CUROA, BĂNG TẢI, SIN PHỐT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 30,
        "MISACode": "0022/0023",
        "Children": [],
        "ProductCategoryNameAndCode": "Dây curoa MITSUBOSHI (MITSUBOSHI)"
      },
      {
        "ID": 12,
        "ProductCategoryName": "Dây curoa, băng tải khác",
        "ProductCategoryCode": "DAYCUROAKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 30,
        "ParentProductCategoryIDText": "DÂY CUROA, BĂNG TẢI, SIN PHỐT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 30,
        "MISACode": "0022/0024",
        "Children": [],
        "ProductCategoryNameAndCode": "Dây curoa, băng tải khác (DAYCUROAKHAC)"
      },
      {
        "ID": 266,
        "ProductCategoryName": "Sin, Phốt",
        "ProductCategoryCode": "SINPHOT",
        "Inactive": false,
        "ParentProductCategoryID": 30,
        "ParentProductCategoryIDText": "DÂY CUROA, BĂNG TẢI, SIN PHỐT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 30,
        "MISACode": "0022/0025",
        "Children": [],
        "ProductCategoryNameAndCode": "Sin, Phốt (SINPHOT)"
      }
    ],
    "ProductCategoryNameAndCode": "DÂY CUROA, BĂNG TẢI, SIN PHỐT (DAYCUROABTSP)"
  },
  {
    "ID": 20,
    "ProductCategoryName": "DÂY XÍCH",
    "ProductCategoryCode": "DAYXICH",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0023",
    "Children": [],
    "ProductCategoryNameAndCode": "DÂY XÍCH (DAYXICH)"
  },
  {
    "ID": 267,
    "ProductCategoryName": "Dụng cụ cầm tay khí nén",
    "ProductCategoryCode": "DCCTKHINEN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0030",
    "Children": [],
    "ProductCategoryNameAndCode": "Dụng cụ cầm tay khí nén (DCCTKHINEN)"
  },
  {
    "ID": 26,
    "ProductCategoryName": "DỤNG CỤ ĐO",
    "ProductCategoryCode": "DUNGCUDO",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0034",
    "Children": [
      {
        "ID": 134,
        "ProductCategoryName": "DỤNG CỤ ĐO INSIZE",
        "ProductCategoryCode": "DUNGCUDOINSIZE",
        "Inactive": false,
        "ParentProductCategoryID": 26,
        "ParentProductCategoryIDText": "DỤNG CỤ ĐO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 26,
        "MISACode": "0034/0034",
        "Children": [],
        "ProductCategoryNameAndCode": "DỤNG CỤ ĐO INSIZE (DUNGCUDOINSIZE)"
      },
      {
        "ID": 101,
        "ProductCategoryName": "DỤNG CỤ ĐO KHÁC",
        "ProductCategoryCode": "DUNGCUDOKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 26,
        "ParentProductCategoryIDText": "DỤNG CỤ ĐO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 26,
        "MISACode": "0034/0035",
        "Children": [],
        "ProductCategoryNameAndCode": "DỤNG CỤ ĐO KHÁC (DUNGCUDOKHAC)"
      },
      {
        "ID": 107,
        "ProductCategoryName": "DỤNG CỤ ĐO MITUTOYO",
        "ProductCategoryCode": "MITUTOYO",
        "Inactive": false,
        "ParentProductCategoryID": 26,
        "ParentProductCategoryIDText": "DỤNG CỤ ĐO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 26,
        "MISACode": "0034/0036",
        "Children": [],
        "ProductCategoryNameAndCode": "DỤNG CỤ ĐO MITUTOYO (MITUTOYO)"
      }
    ],
    "ProductCategoryNameAndCode": "DỤNG CỤ ĐO (DUNGCUDO)"
  },
  {
    "ID": 130,
    "ProductCategoryName": "HÀNG GIA CÔNG",
    "ProductCategoryCode": "HANGIACONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0040",
    "Children": [],
    "ProductCategoryNameAndCode": "HÀNG GIA CÔNG (HANGIACONG)"
  },
  {
    "ID": 247,
    "ProductCategoryName": "Máy cầm tay Trung Quốc",
    "ProductCategoryCode": "MAYCAMTAYTQ",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0045",
    "Children": [],
    "ProductCategoryNameAndCode": "Máy cầm tay Trung Quốc (MAYCAMTAYTQ)"
  },
  {
    "ID": 74,
    "ProductCategoryName": "MÁY DÙNG HƠI",
    "ProductCategoryCode": "MAYDUNGHOI",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0051",
    "Children": [],
    "ProductCategoryNameAndCode": "MÁY DÙNG HƠI (MAYDUNGHOI)"
  },
  {
    "ID": 180,
    "ProductCategoryName": "MÁY, PHỤ KIỆN MÁY HÀN",
    "ProductCategoryCode": "MÁY HÀN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0077",
    "Children": [
      {
        "ID": 182,
        "ProductCategoryName": "Máy hàn và phụ kiện hàn HỒNG KÝ",
        "ProductCategoryCode": "HONGKY",
        "Inactive": false,
        "ParentProductCategoryID": 180,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN MÁY HÀN",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 180,
        "MISACode": "0077/0077",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy hàn và phụ kiện hàn HỒNG KÝ (HONGKY)"
      },
      {
        "ID": 181,
        "ProductCategoryName": "Máy hàn và phụ kiện hàn JASIC",
        "ProductCategoryCode": "JASIC",
        "Inactive": false,
        "ParentProductCategoryID": 180,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN MÁY HÀN",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 180,
        "MISACode": "0077/0078",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy hàn và phụ kiện hàn JASIC (JASIC)"
      },
      {
        "ID": 183,
        "ProductCategoryName": "Máy hàn và phụ kiện hàn Khác",
        "ProductCategoryCode": "MAYHANKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 180,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN MÁY HÀN",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 180,
        "MISACode": "0077/0079",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy hàn và phụ kiện hàn Khác (MAYHANKHAC)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN MÁY HÀN (MÁY HÀN)"
  },
  {
    "ID": 160,
    "ProductCategoryName": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
    "ProductCategoryCode": "BOSCH",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0078",
    "Children": [
      {
        "ID": 222,
        "ProductCategoryName": "Máy điện Bosch",
        "ProductCategoryCode": "MAYDIENBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0078",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy điện Bosch (MAYDIENBOSCH)"
      },
      {
        "ID": 223,
        "ProductCategoryName": "Máy đo Bosch",
        "ProductCategoryCode": "MAYDOBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0079",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy đo Bosch (MAYDOBOSCH)"
      },
      {
        "ID": 221,
        "ProductCategoryName": "Máy pin Bosch",
        "ProductCategoryCode": "MAYPINBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0080",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy pin Bosch (MAYPINBOSCH)"
      },
      {
        "ID": 224,
        "ProductCategoryName": "Phụ kiện Bosch",
        "ProductCategoryCode": "PKBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0081",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện Bosch (PKBOSCH)"
      },
      {
        "ID": 231,
        "ProductCategoryName": "Phụ tùng Bosch",
        "ProductCategoryCode": "PTBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0082",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ tùng Bosch (PTBOSCH)"
      },
      {
        "ID": 228,
        "ProductCategoryName": "Quà tặng Bosch",
        "ProductCategoryCode": "QTBOSCH",
        "Inactive": false,
        "ParentProductCategoryID": 160,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 160,
        "MISACode": "0078/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Quà tặng Bosch (QTBOSCH)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC BOSCH (BOSCH)"
  },
  {
    "ID": 172,
    "ProductCategoryName": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC DEWALT",
    "ProductCategoryCode": "DEWALT",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0079",
    "Children": [
      {
        "ID": 173,
        "ProductCategoryName": "Công cụ, cụng cụ  DEWALT",
        "ProductCategoryCode": "CCDCDEWALT",
        "Inactive": false,
        "ParentProductCategoryID": 172,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC DEWALT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 172,
        "MISACode": "0079/0080",
        "Children": [],
        "ProductCategoryNameAndCode": "Công cụ, cụng cụ  DEWALT (CCDCDEWALT)"
      },
      {
        "ID": 174,
        "ProductCategoryName": "Máy  DEWALT",
        "ProductCategoryCode": "MAYDEWALT",
        "Inactive": false,
        "ParentProductCategoryID": 172,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC DEWALT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 172,
        "MISACode": "0079/0082",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy  DEWALT (MAYDEWALT)"
      },
      {
        "ID": 175,
        "ProductCategoryName": "Phụ kiện DEWALT",
        "ProductCategoryCode": "PKDEWALT",
        "Inactive": false,
        "ParentProductCategoryID": 172,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC DEWALT",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 172,
        "MISACode": "0079/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện DEWALT (PKDEWALT)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC DEWALT (DEWALT)"
  },
  {
    "ID": 168,
    "ProductCategoryName": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
    "ProductCategoryCode": "MAKITA",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0080",
    "Children": [
      {
        "ID": 171,
        "ProductCategoryName": "Công cụ, cụng cụ MAKITA",
        "ProductCategoryCode": "CCDCMAKITA",
        "Inactive": false,
        "ParentProductCategoryID": 168,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 168,
        "MISACode": "0080/0080",
        "Children": [],
        "ProductCategoryNameAndCode": "Công cụ, cụng cụ MAKITA (CCDCMAKITA)"
      },
      {
        "ID": 170,
        "ProductCategoryName": "Máy điện MAKITA",
        "ProductCategoryCode": "MAYDIENMAKITA",
        "Inactive": false,
        "ParentProductCategoryID": 168,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 168,
        "MISACode": "0080/0081",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy điện MAKITA (MAYDIENMAKITA)"
      },
      {
        "ID": 234,
        "ProductCategoryName": "Máy pin MAKITA",
        "ProductCategoryCode": "MAYPINMAKITA",
        "Inactive": false,
        "ParentProductCategoryID": 168,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 168,
        "MISACode": "0080/0082",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy pin MAKITA (MAYPINMAKITA)"
      },
      {
        "ID": 169,
        "ProductCategoryName": "Phụ kiện MAKITA",
        "ProductCategoryCode": "PKMAKITA",
        "Inactive": false,
        "ParentProductCategoryID": 168,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 168,
        "MISACode": "0080/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện MAKITA (PKMAKITA)"
      },
      {
        "ID": 235,
        "ProductCategoryName": "Phụ tùng MAKITA",
        "ProductCategoryCode": "PTMAKITA",
        "Inactive": false,
        "ParentProductCategoryID": 168,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 168,
        "MISACode": "0080/0084",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ tùng MAKITA (PTMAKITA)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MAKITA (MAKITA)"
  },
  {
    "ID": 164,
    "ProductCategoryName": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
    "ProductCategoryCode": "MILWAUKEE",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0081",
    "Children": [
      {
        "ID": 165,
        "ProductCategoryName": "Công cụ, dụng cụ Milwaukee",
        "ProductCategoryCode": "CCDCMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0082",
        "Children": [],
        "ProductCategoryNameAndCode": "Công cụ, dụng cụ Milwaukee (CCDCMIL)"
      },
      {
        "ID": 166,
        "ProductCategoryName": "Máy Milwaukee",
        "ProductCategoryCode": "MAYMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy Milwaukee (MAYMIL)"
      },
      {
        "ID": 226,
        "ProductCategoryName": "Packout Milwaukee",
        "ProductCategoryCode": "PACKOUTMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0084",
        "Children": [],
        "ProductCategoryNameAndCode": "Packout Milwaukee (PACKOUTMIL)"
      },
      {
        "ID": 238,
        "ProductCategoryName": "Phụ kiện Milwaukee",
        "ProductCategoryCode": "PKMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0085",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện Milwaukee (PKMIL)"
      },
      {
        "ID": 167,
        "ProductCategoryName": "Phụ tùng Milwaukee",
        "ProductCategoryCode": "PTMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0086",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ tùng Milwaukee (PTMIL)"
      },
      {
        "ID": 227,
        "ProductCategoryName": "Quà tặng Milwaukee",
        "ProductCategoryCode": "QTMIL",
        "Inactive": false,
        "ParentProductCategoryID": 164,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 164,
        "MISACode": "0081/0087",
        "Children": [],
        "ProductCategoryNameAndCode": "Quà tặng Milwaukee (QTMIL)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC MILWAUKEE (MILWAUKEE)"
  },
  {
    "ID": 176,
    "ProductCategoryName": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC STANLEY",
    "ProductCategoryCode": "STANLEY",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0082",
    "Children": [
      {
        "ID": 177,
        "ProductCategoryName": "Công cụ, cụng cụ STANLEY",
        "ProductCategoryCode": "CCDCSTANLEY",
        "Inactive": false,
        "ParentProductCategoryID": 176,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC STANLEY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 176,
        "MISACode": "0082/0082",
        "Children": [],
        "ProductCategoryNameAndCode": "Công cụ, cụng cụ STANLEY (CCDCSTANLEY)"
      },
      {
        "ID": 178,
        "ProductCategoryName": "Máy  STANLEY",
        "ProductCategoryCode": "MAYSTANLEY",
        "Inactive": false,
        "ParentProductCategoryID": 176,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC STANLEY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 176,
        "MISACode": "0082/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Máy  STANLEY (MAYSTANLEY)"
      },
      {
        "ID": 179,
        "ProductCategoryName": "Phụ kiện,phụ tùng STANLEY",
        "ProductCategoryCode": "PKPTSTANLEY",
        "Inactive": false,
        "ParentProductCategoryID": 176,
        "ParentProductCategoryIDText": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC STANLEY",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 176,
        "MISACode": "0082/0084",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện,phụ tùng STANLEY (PKPTSTANLEY)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY, PHỤ KIỆN, PHỤ TÙNG, CCDC STANLEY (STANLEY)"
  },
  {
    "ID": 241,
    "ProductCategoryName": "MÁY,PHỤ KIỆN, PHỤ TÙNG KARCHER",
    "ProductCategoryCode": "KARCHER",
    "Inactive": false,
    "OrganizationUnitID": 17,
    "OrganizationUnitIDText": "PHÒNG KINH DOANH ĐÀ NẴNG",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0083",
    "Children": [
      {
        "ID": 246,
        "ProductCategoryName": "Công nghiệp KARCHER",
        "ProductCategoryCode": "KARCHER-CN",
        "Inactive": false,
        "ParentProductCategoryID": 241,
        "ParentProductCategoryIDText": "MÁY,PHỤ KIỆN, PHỤ TÙNG KARCHER",
        "OrganizationUnitID": 17,
        "OrganizationUnitIDText": "PHÒNG KINH DOANH ĐÀ NẴNG",
        "IsDisplayed": true,
        "ParentID": 241,
        "MISACode": "0083/0083",
        "Children": [],
        "ProductCategoryNameAndCode": "Công nghiệp KARCHER (KARCHER-CN)"
      },
      {
        "ID": 245,
        "ProductCategoryName": "Dân dụng KARCHER",
        "ProductCategoryCode": "KARCHER-DANDUNG",
        "Inactive": false,
        "ParentProductCategoryID": 241,
        "ParentProductCategoryIDText": "MÁY,PHỤ KIỆN, PHỤ TÙNG KARCHER",
        "OrganizationUnitID": 17,
        "OrganizationUnitIDText": "PHÒNG KINH DOANH ĐÀ NẴNG",
        "IsDisplayed": true,
        "ParentID": 241,
        "MISACode": "0083/0084",
        "Children": [
          {
            "ID": 259,
            "ProductCategoryName": "Hoá chất vệ sinh KARCHER",
            "ProductCategoryCode": "KARCHER-HC",
            "Inactive": false,
            "ParentProductCategoryID": 245,
            "ParentProductCategoryIDText": "Dân dụng KARCHER",
            "OrganizationUnitID": 1,
            "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
            "IsDisplayed": true,
            "ParentID": 245,
            "MISACode": "0083/0084/0084",
            "Children": [],
            "ProductCategoryNameAndCode": "Hoá chất vệ sinh KARCHER (KARCHER-HC)"
          }
        ],
        "ProductCategoryNameAndCode": "Dân dụng KARCHER (KARCHER-DANDUNG)"
      }
    ],
    "ProductCategoryNameAndCode": "MÁY,PHỤ KIỆN, PHỤ TÙNG KARCHER (KARCHER)"
  },
  {
    "ID": 127,
    "ProductCategoryName": "PHÍ HÓDƠN",
    "ProductCategoryCode": "PHIKHAC",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0090",
    "Children": [],
    "ProductCategoryNameAndCode": "PHÍ HÓA ĐƠN (PHIKHAC)"
  },
  {
    "ID": 100,
    "ProductCategoryName": "PHÍCH CẮM & Ổ CẮM CÔNG NGHIỆP",
    "ProductCategoryCode": "PHICHCAMVAOCAMCONGNGHIEP",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0091",
    "Children": [],
    "ProductCategoryNameAndCode": "PHÍCH CẮM & Ổ CẮM CÔNG NGHIỆP (PHICHCAMVAOCAMCONGNGHIEP)"
  },
  {
    "ID": 34,
    "ProductCategoryName": "PHỤ KIỆN DÂY CUROA",
    "ProductCategoryCode": "PHUKIENDAYCUROA",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0092",
    "Children": [],
    "ProductCategoryNameAndCode": "PHỤ KIỆN DÂY CUROA (PHUKIENDAYCUROA)"
  },
  {
    "ID": 7,
    "ProductCategoryName": "PHỤ KIỆN ĐƯỜNG ỐNG",
    "ProductCategoryCode": "PHUKIENDUONGONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0093",
    "Children": [],
    "ProductCategoryNameAndCode": "PHỤ KIỆN ĐƯỜNG ỐNG (PHUKIENDUONGONG)"
  },
  {
    "ID": 5,
    "ProductCategoryName": "PHỤ KIỆN PHỤ TÙNG MÁY PIN",
    "ProductCategoryCode": "PHUKIENPHUTUNGMAYPIN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0096",
    "Children": [],
    "ProductCategoryNameAndCode": "PHỤ KIỆN PHỤ TÙNG MÁY PIN (PHUKIENPHUTUNGMAYPIN)"
  },
  {
    "ID": 199,
    "ProductCategoryName": "PHỤ KIỆN TRUYỀN ĐỘNG",
    "ProductCategoryCode": "PHUKIENTRUYENDONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0097",
    "Children": [
      {
        "ID": 16,
        "ProductCategoryName": "Puly, nhông, xích, khớp nối",
        "ProductCategoryCode": "PULY,BANHRANG,KHOPNOI",
        "Inactive": false,
        "ParentProductCategoryID": 199,
        "ParentProductCategoryIDText": "PHỤ KIỆN TRUYỀN ĐỘNG",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 199,
        "MISACode": "0097/0100",
        "Children": [],
        "ProductCategoryNameAndCode": "Puly, nhông, xích, khớp nối (PULY,BANHRANG,KHOPNOI)"
      }
    ],
    "ProductCategoryNameAndCode": "PHỤ KIỆN TRUYỀN ĐỘNG (PHUKIENTRUYENDONG)"
  },
  {
    "ID": 57,
    "ProductCategoryName": "PHỤ TÙNG PHỤ KIÊN MÁY ĐIỆN",
    "ProductCategoryCode": "PHUTUNGPHUKIENMAYDIEN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0098",
    "Children": [],
    "ProductCategoryNameAndCode": "PHỤ TÙNG PHỤ KIÊN MÁY ĐIỆN (PHUTUNGPHUKIENMAYDIEN)"
  },
  {
    "ID": 95,
    "ProductCategoryName": "QUÀ HÃNG TẶNG KÈM",
    "ProductCategoryCode": "QUATANG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0101",
    "Children": [],
    "ProductCategoryNameAndCode": "QUÀ HÃNG TẶNG KÈM (QUATANG)"
  },
  {
    "ID": 132,
    "ProductCategoryName": "SẮT THÉP INOX",
    "ProductCategoryCode": "SAT-THEP-INOX",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0103",
    "Children": [],
    "ProductCategoryNameAndCode": "SẮT THÉP INOX (SAT-THEP-INOX)"
  },
  {
    "ID": 243,
    "ProductCategoryName": "SKF",
    "ProductCategoryCode": "HANGSKF",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0105",
    "Children": [
      {
        "ID": 237,
        "ProductCategoryName": "MỠ SKF",
        "ProductCategoryCode": "MOSKF",
        "Inactive": false,
        "ParentProductCategoryID": 243,
        "ParentProductCategoryIDText": "SKF",
        "OrganizationUnitID": 5,
        "OrganizationUnitIDText": "PHÒNG KHO VẬN",
        "IsDisplayed": true,
        "ParentID": 243,
        "MISACode": "0105/0106",
        "Children": [],
        "ProductCategoryNameAndCode": "MỠ SKF (MOSKF)"
      },
      {
        "ID": 184,
        "ProductCategoryName": "Vòng bi, gối đỡ và phụ kiện SKF",
        "ProductCategoryCode": "VONGBIVAGOIDOSKF",
        "Inactive": false,
        "ParentProductCategoryID": 243,
        "ParentProductCategoryIDText": "SKF",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 243,
        "MISACode": "0105/0107",
        "Children": [],
        "ProductCategoryNameAndCode": "Vòng bi, gối đỡ và phụ kiện SKF (VONGBIVAGOIDOSKF)"
      }
    ],
    "ProductCategoryNameAndCode": "SKF (HANGSKF)"
  },
  {
    "ID": 212,
    "ProductCategoryName": "Thiết bị điện",
    "ProductCategoryCode": "DIENCONGNGHIEP",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0107",
    "Children": [
      {
        "ID": 218,
        "ProductCategoryName": "Thiết bị điện cho tủ điện",
        "ProductCategoryCode": "THIETBITUDIEN",
        "Inactive": false,
        "ParentProductCategoryID": 212,
        "ParentProductCategoryIDText": "Thiết bị điện",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 212,
        "MISACode": "0107/0107",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị điện cho tủ điện (THIETBITUDIEN)"
      },
      {
        "ID": 254,
        "ProductCategoryName": "Thiết bị điện chuyên dụng",
        "ProductCategoryCode": "THIETBIDIENCHUYENDUNG",
        "Inactive": false,
        "ParentProductCategoryID": 212,
        "ParentProductCategoryIDText": "Thiết bị điện",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 212,
        "MISACode": "0107/0108",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị điện chuyên dụng (THIETBIDIENCHUYENDUNG)"
      },
      {
        "ID": 11,
        "ProductCategoryName": "Thiết bị điện lắp ngoài",
        "ProductCategoryCode": "THIETBIDIENLAPNGOAI",
        "Inactive": false,
        "ParentProductCategoryID": 212,
        "ParentProductCategoryIDText": "Thiết bị điện",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 212,
        "MISACode": "0107/0111",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị điện lắp ngoài (THIETBIDIENLAPNGOAI)"
      },
      {
        "ID": 256,
        "ProductCategoryName": "Thiết bị điện mặt trời",
        "ProductCategoryCode": "THIETBIDIENMATTROI",
        "Inactive": false,
        "ParentProductCategoryID": 212,
        "ParentProductCategoryIDText": "Thiết bị điện",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 212,
        "MISACode": "0107/0112",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị điện mặt trời (THIETBIDIENMATTROI)"
      },
      {
        "ID": 255,
        "ProductCategoryName": "Thiết bị đo điện",
        "ProductCategoryCode": "THIETBIDODIEN",
        "Inactive": false,
        "ParentProductCategoryID": 212,
        "ParentProductCategoryIDText": "Thiết bị điện",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 212,
        "MISACode": "0107/0113",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị đo điện (THIETBIDODIEN)"
      }
    ],
    "ProductCategoryNameAndCode": "Thiết bị điện (DIENCONGNGHIEP)"
  },
  {
    "ID": 69,
    "ProductCategoryName": "THIẾT BỊ ĐƯỜNG ỐNG",
    "ProductCategoryCode": "THIETBIDUONGONG",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0111",
    "Children": [
      {
        "ID": 208,
        "ProductCategoryName": "Thiết bị đường ống kim loại",
        "ProductCategoryCode": "DUONGONGKIMLOAI",
        "Inactive": false,
        "ParentProductCategoryID": 69,
        "ParentProductCategoryIDText": "THIẾT BỊ ĐƯỜNG ỐNG",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 69,
        "MISACode": "0111/0111",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị đường ống kim loại (DUONGONGKIMLOAI)"
      },
      {
        "ID": 209,
        "ProductCategoryName": "Thiết bị đường ống nhựa",
        "ProductCategoryCode": "DUONGONGNHUA",
        "Inactive": false,
        "ParentProductCategoryID": 69,
        "ParentProductCategoryIDText": "THIẾT BỊ ĐƯỜNG ỐNG",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 69,
        "MISACode": "0111/0112",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị đường ống nhựa (DUONGONGNHUA)"
      },
      {
        "ID": 253,
        "ProductCategoryName": "Thiết bị đường ống thuỷ lực",
        "ProductCategoryCode": "DUONGONGTHUYLUC",
        "Inactive": false,
        "ParentProductCategoryID": 69,
        "ParentProductCategoryIDText": "THIẾT BỊ ĐƯỜNG ỐNG",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 69,
        "MISACode": "0111/0113",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị đường ống thuỷ lực (DUONGONGTHUYLUC)"
      }
    ],
    "ProductCategoryNameAndCode": "THIẾT BỊ ĐƯỜNG ỐNG (THIETBIDUONGONG)"
  },
  {
    "ID": 125,
    "ProductCategoryName": "THIẾT BỊ KHÍ NÉN",
    "ProductCategoryCode": "PM_THIETBIKHINEN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0113",
    "Children": [],
    "ProductCategoryNameAndCode": "THIẾT BỊ KHÍ NÉN (PM_THIETBIKHINEN)"
  },
  {
    "ID": 1,
    "ProductCategoryName": "TỦ ĐIỆN & PHỤ KIỆN TỦ ĐIỆN",
    "ProductCategoryCode": "TUDIENVAPHUKIENTUDIEN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0114",
    "Children": [],
    "ProductCategoryNameAndCode": "TỦ ĐIỆN & PHỤ KIỆN TỦ ĐIỆN (TUDIENVAPHUKIENTUDIEN)"
  },
  {
    "ID": 99,
    "ProductCategoryName": "TỦ VÀ THIẾT BỊ NÂNG HẠ",
    "ProductCategoryCode": "TU,THIETBINANGHA",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0116",
    "Children": [
      {
        "ID": 206,
        "ProductCategoryName": "Thiết bị nâng hạ khác",
        "ProductCategoryCode": "THIETBINANGKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 99,
        "ParentProductCategoryIDText": "TỦ VÀ THIẾT BỊ NÂNG HẠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 99,
        "MISACode": "0116/0117",
        "Children": [],
        "ProductCategoryNameAndCode": "Thiết bị nâng hạ khác (THIETBINANGKHAC)"
      },
      {
        "ID": 118,
        "ProductCategoryName": "TỦ ĐỒ NGHỀ CSPS",
        "ProductCategoryCode": "CSPS",
        "Inactive": false,
        "ParentProductCategoryID": 99,
        "ParentProductCategoryIDText": "TỦ VÀ THIẾT BỊ NÂNG HẠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 99,
        "MISACode": "0116/0118",
        "Children": [],
        "ProductCategoryNameAndCode": "TỦ ĐỒ NGHỀ CSPS (CSPS)"
      },
      {
        "ID": 205,
        "ProductCategoryName": "XE NÂNG VÀ PHỤ KIỆN XE NÂNG CÁC HÃNG",
        "ProductCategoryCode": "XENANG",
        "Inactive": false,
        "ParentProductCategoryID": 99,
        "ParentProductCategoryIDText": "TỦ VÀ THIẾT BỊ NÂNG HẠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 99,
        "MISACode": "0116/0119",
        "Children": [],
        "ProductCategoryNameAndCode": "XE NÂNG VÀ PHỤ KIỆN XE NÂNG CÁC HÃNG (XENANG)"
      }
    ],
    "ProductCategoryNameAndCode": "TỦ VÀ THIẾT BỊ NÂNG HẠ (TU,THIETBINANGHA)"
  },
  {
    "ID": 190,
    "ProductCategoryName": "VẬT TƯ KHÍ NÉN",
    "ProductCategoryCode": "VATTKHINEN",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0122",
    "Children": [
      {
        "ID": 53,
        "ProductCategoryName": "VẬT TƯ KHÍ NÉN KHÁC",
        "ProductCategoryCode": "VATTUKHINENKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 190,
        "ParentProductCategoryIDText": "VẬT TƯ KHÍ NÉN",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 190,
        "MISACode": "0122/0123",
        "Children": [],
        "ProductCategoryNameAndCode": "VẬT TƯ KHÍ NÉN KHÁC (VATTUKHINENKHAC)"
      },
      {
        "ID": 141,
        "ProductCategoryName": "VẬT TƯ KHÍ NÉN SMC",
        "ProductCategoryCode": "KHINENSMC",
        "Inactive": false,
        "ParentProductCategoryID": 190,
        "ParentProductCategoryIDText": "VẬT TƯ KHÍ NÉN",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 190,
        "MISACode": "0122/0126",
        "Children": [],
        "ProductCategoryNameAndCode": "VẬT TƯ KHÍ NÉN SMC (KHINENSMC)"
      }
    ],
    "ProductCategoryNameAndCode": "VẬT TƯ KHÍ NÉN (VATTKHINEN)"
  },
  {
    "ID": 153,
    "ProductCategoryName": "VẬT TƯ KHÍ NÉN-xoá",
    "ProductCategoryCode": "VATTKHINEN_ACT1",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0123",
    "Children": [],
    "ProductCategoryNameAndCode": "VẬT TƯ KHÍ NÉN-xoá (VATTKHINEN_ACT1)"
  },
  {
    "ID": 19,
    "ProductCategoryName": "VẬT TƯ TIÊU HAO",
    "ProductCategoryCode": "VATTUTIEUHAO",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀ LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0124",
    "Children": [
      {
        "ID": 261,
        "ProductCategoryName": "Bánh xe đẩy công nghiệp",
        "ProductCategoryCode": "BANHXEDAY",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0124",
        "Children": [],
        "ProductCategoryNameAndCode": "Bánh xe đẩy công nghiệp (BANHXEDAY)"
      },
      {
        "ID": 54,
        "ProductCategoryName": "BẢO HỘ LAO ĐỘNG",
        "ProductCategoryCode": "BAOHOLAODONG",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0125",
        "Children": [],
        "ProductCategoryNameAndCode": "BẢO HỘ LAO ĐỘNG (BAOHOLAODONG)"
      },
      {
        "ID": 262,
        "ProductCategoryName": "Bình accquy, pin",
        "ProductCategoryCode": "ACCQUY",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0126",
        "Children": [],
        "ProductCategoryNameAndCode": "Bình accquy, pin (ACCQUY)"
      },
      {
        "ID": 210,
        "ProductCategoryName": "Đá cắt, đá mài, nhám xếp",
        "ProductCategoryCode": "DAMAICAT",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0127",
        "Children": [],
        "ProductCategoryNameAndCode": "Đá cắt, đá mài, nhám xếp (DAMAICAT)"
      },
      {
        "ID": 264,
        "ProductCategoryName": "Keo dán, Silicone",
        "ProductCategoryCode": "KEODAN",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0128",
        "Children": [],
        "ProductCategoryNameAndCode": "Keo dán, Silicone (KEODAN)"
      },
      {
        "ID": 260,
        "ProductCategoryName": "Lưỡi cắt, cưa",
        "ProductCategoryCode": "LUOICAT",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0129",
        "Children": [],
        "ProductCategoryNameAndCode": "Lưỡi cắt, cưa (LUOICAT)"
      },
      {
        "ID": 211,
        "ProductCategoryName": "Mũi khoan, mũi taro, mũi phay",
        "ProductCategoryCode": "MUIKHOANTARO",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0130",
        "Children": [],
        "ProductCategoryNameAndCode": "Mũi khoan, mũi taro, mũi phay (MUIKHOANTARO)"
      },
      {
        "ID": 263,
        "ProductCategoryName": "Nguyên liệu gia công",
        "ProductCategoryCode": "NGUYENLIEUGIACONG",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0133",
        "Children": [],
        "ProductCategoryNameAndCode": "Nguyên liệu gia công (NGUYENLIEUGIACONG)"
      },
      {
        "ID": 220,
        "ProductCategoryName": "Sơn và phụ kiện",
        "ProductCategoryCode": "SON",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0134",
        "Children": [],
        "ProductCategoryNameAndCode": "Sơn và phụ kiện (SON)"
      },
      {
        "ID": 265,
        "ProductCategoryName": "Vật tư đóng gói",
        "ProductCategoryCode": "VATTUDONGGOI",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0135",
        "Children": [],
        "ProductCategoryNameAndCode": "Vật tư đóng gói (VATTUDONGGOI)"
      },
      {
        "ID": 207,
        "ProductCategoryName": "Vật tư vệ sinh làm sạch",
        "ProductCategoryCode": "VATTUVESINH",
        "Inactive": false,
        "ParentProductCategoryID": 19,
        "ParentProductCategoryIDText": "VẬT TƯ TIÊU HAO",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 19,
        "MISACode": "0124/0136",
        "Children": [],
        "ProductCategoryNameAndCode": "Vật tư vệ sinh làm sạch (VATTUVESINH)"
      }
    ],
    "ProductCategoryNameAndCode": "VẬT TƯ TIÊU HAO (VATTUTIEUHAO)"
  },
  {
    "ID": 145,
    "ProductCategoryName": "VÍT GỖ-TÔN, TẮC KÊ SẮT-INOX-NHỰA",
    "ProductCategoryCode": "VITTACKE",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0127",
    "Children": [],
    "ProductCategoryNameAndCode": "VÍT GỖ-TÔN, TẮC KÊ SẮT-INOX-NHỰA (VITTACKE)"
  },
  {
    "ID": 4,
    "ProductCategoryName": "VÒNG BI VÀ GỐI ĐỠ",
    "ProductCategoryCode": "VONGBIGOIDO",
    "Inactive": false,
    "OrganizationUnitID": 1,
    "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
    "IsDisplayed": true,
    "ParentID": 0,
    "MISACode": "0129",
    "Children": [
      {
        "ID": 187,
        "ProductCategoryName": "Gối đỡ ASAHI",
        "ProductCategoryCode": "ASAHI",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0129",
        "Children": [],
        "ProductCategoryNameAndCode": "Gối đỡ ASAHI (ASAHI)"
      },
      {
        "ID": 189,
        "ProductCategoryName": "Phụ kiện vòng bi và gối đỡ",
        "ProductCategoryCode": "PHUKIENVONGBI",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0130",
        "Children": [],
        "ProductCategoryNameAndCode": "Phụ kiện vòng bi và gối đỡ (PHUKIENVONGBI)"
      },
      {
        "ID": 188,
        "ProductCategoryName": "Vòng bi và gối đỡ khác",
        "ProductCategoryCode": "VONGBIKHAC",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0131",
        "Children": [],
        "ProductCategoryNameAndCode": "Vòng bi và gối đỡ khác (VONGBIKHAC)"
      },
      {
        "ID": 185,
        "ProductCategoryName": "Vòng bi và gối đỡ KOYO",
        "ProductCategoryCode": "KOYO",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0132",
        "Children": [],
        "ProductCategoryNameAndCode": "Vòng bi và gối đỡ KOYO (KOYO)"
      },
      {
        "ID": 186,
        "ProductCategoryName": "Vòng bi và gối đỡ NTN",
        "ProductCategoryCode": "NTN",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0133",
        "Children": [],
        "ProductCategoryNameAndCode": "Vòng bi và gối đỡ NTN (NTN)"
      },
      {
        "ID": 6,
        "ProductCategoryName": "Vòng bi, gối đỡ và phụ kiện các hãng Nhật",
        "ProductCategoryCode": "KOYO, ASAHI, NTN, NSK",
        "Inactive": false,
        "ParentProductCategoryID": 4,
        "ParentProductCategoryIDText": "VÒNG BI VÀ GỐI ĐỠ",
        "OrganizationUnitID": 1,
        "OrganizationUnitIDText": "CÔNG TY TNHH VI NA HOÀNG LONG VŨ",
        "IsDisplayed": true,
        "ParentID": 4,
        "MISACode": "0129/0134",
        "Children": [],
        "ProductCategoryNameAndCode": "Vòng bi, gối đỡ và phụ kiện các hãng Nhật (KOYO, ASAHI, NTN, NSK)"
      }
    ],
    "ProductCategoryNameAndCode": "VÒNG BI VÀ GỐI ĐỠ (VONGBIGOIDO)"
  }
]