{
    'name': 'HLV Sale Delivery Planning',
    'version': '18.0.1.0.0',
    'summary': 'Điều phối giao hàng: Bán hàng -> Mua hàng',
    'description': 'Dashboard trực quan bằng OWL quản lý kế hoạch giao hàng từ đơn bán và tiến độ hàng từ đơn mua.',
    'category': 'Sales',
    'author': 'HLV',
    'depends': ['sale_management', 'purchase_stock', 'bus'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/delivery_planner_cron.xml',
        'views/res_config_settings_views.xml',
        'views/res_users_views.xml',
        'views/delivery_planner_views.xml',
        'views/picking_packer_wizard_views.xml',
        'views/sale_plan_bus_templates.xml',
    ],
    'assets': {
        'hlv_sale_delivery_planning.assets_sale_plan_bus': [
            'hlv_sale_delivery_planning/static/src/sale_plan_bus/sale_plan_bus_frame.js',
        ],
        'web.assets_backend': [
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner.scss',
            # Sub-templates (phải đăng ký trước main template)
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_kpi.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_filters.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_so_card.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_drawer.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_modal.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_kanban.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_table.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_transfer_modal.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_relocation_modal.xml',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_packer_modal.xml',
            'hlv_sale_delivery_planning/static/src/components/packing_kpi/packing_kpi.xml',
            # Main template
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner.xml',
            # JS utils (phải đăng ký trước main component)
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_utils.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_realtime_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_data_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_cache_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_preferences_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_table_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_kanban_selection_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_printing_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_display_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_display_helpers_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_drawer_messages_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_transfer_mixin.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner_relocation_mixin.js',
            'hlv_sale_delivery_planning/static/src/report/picking_packer_assignment_handler.js',
            'hlv_sale_delivery_planning/static/src/components/delivery_planner/delivery_planner.js',
            'hlv_sale_delivery_planning/static/src/components/packing_kpi/packing_kpi.js',
        ],
    },
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
