from . import sale_order
from . import res_users
from . import res_config_settings
from . import stock_picking
from . import stock_move
from . import ir_actions_report
from . import delivery_planner_message
from . import delivery_planner_user_pref
from . import delivery_planner_snapshot
from . import picking_packer_wizard
from . import sale_plan_mention_notification
from . import sale_plan_web_push_subscription
