{
    "name": "AMIS Callback Verified",
    "version": "1.4",
    "category": "Custom",
    "summary": "Nhận callback từ MISA, xác thực chữ ký SHA256 HMAC và xem log trong Odoo",
    "author": "ChatGPT",
    "depends": ["base", "stock", "purchase", "sale", "mail"],
    "data": [
        "security/res_groups.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/ir_cron.xml",
        "data/shopee_webhook_status_data.xml",
        "data/meinvoice_mail_data.xml",
        "views/misa_invoice_template_wizard_views.xml",
        "views/meinvoice_publish_wizard_views.xml",
        "views/shopee_wallet_import_wizard_views.xml",
        "views/webhook_queue_views.xml",
        "views/amis_callback_views.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "license": "LGPL-3"
}
